config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index' 
  get 'recipes/about'
  get 'recipes/services'
  get 'recipes/contact'
  get 'recipes/login' 
  root 'recipes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    include HTTParty

    base_uri 'http://www.recipepuppy.com/api'
    default_params onlyImages: 1 
    format:json

    def self.for(keyword = 'Chocolate')
        get('', query: {q: keyword})['results']
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @search = params[:search] || 'CHOCOLATE'
    @recipes = Recipe.for(@search)
  end

  def about
  end

  def services
  end

  def contact
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
    <%= yield %>
  </body>
</html>

app/views/recipes/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <%= link_to 'RECIPES', recipes_index_path, class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
      <%= link_to 'Home', recipes_index_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', recipes_about_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'Services', recipes_services_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'Contact', recipes_contact_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'Login', recipes_login_path, class:'btn btn-warning' %>
      </li>
    </ul>
  </div>
</nav>

app/views/recipes/about.html.erb
<%= render 'recipes/navbar.html.erb' %>
<h1>Recipes#about</h1>
<p>Find me in app/views/recipes/about.html.erb</p>

app/views/recipes/contact.html.erb
<%= render 'recipes/navbar.html.erb' %>

app/views/recipes/index.html.erb
<%= render 'recipes/navbar.html.erb' %>

<section class="container-fluid mb-5 mt-5">
<h1>ENJOY A  <%= @search %> RECIPE</h1>

<table border="1" role="table">
    <tr class="text-center">
        <th>Image</th>
        <th>Title</th>
        <th>Ingredients</th>
    </tr>
    <% @recipes.each do |recipe| %>
        <tr class="text-center">
            <td><%= link_to image_tag(recipe['thumbnail'],size: "80x80"), recipe['href'] %></td>
            <td><%= link_to (recipe['title']), recipe['href'] %></td>
            <td><%= recipe['ingredients'] %></td>
        </tr>
    <% end %>
</table>
</section>

app/views/recipes/login.html.erb
<%= render 'recipes/navbar.html.erb' %>
<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body class="contact_body text-center">
    <form class="container login" >
    <div class="form-group">
      <%= image_tag 'vibe.png', class:'vibes' %>
    </div>
    <div class="form-group">
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email address" required >
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-labels" for="exampleCheck1">Remember me</label>
    </div>
      <%= link_to 'Submit', root_path, class:"btn btn-primary login_btn " %>
  </form>
</body>
</html>

app/views/recipes/services.html.erb
<%= render 'recipes/navbar.html.erb' %>
<h1>Recipes#services</h1>
<p>Find me in app/views/recipes/services.html.erb</p>